### ISSUE TITLE
Question!!

### ISSUE THREAD

**Issue by nico281** [juicyapp/cordova-plugins-justmusicplayer#3]
Hi, how are you? i don't understand how install the plugin in my proyect.
Where i put the https://github.com/juicyapp/cordova-plugins-justmusicplayer.git?
Could you help me?

Cheers!!

**Comment by walaman** [comment]
Hi @nico281 , 
You may try run this command on your cordova project
`cordova plugin add https://github.com/juicyapp/cordova-plugins-justmusicplayer.git`

For more detail info on installing plugin you may take a look on 
https://cordova.apache.org/docs/en/5.4.0/guide/cli/index.html 

Since this project is still WIP, it is not yet registered in [apache plugin registry](https://cordova.apache.org/news/2013/10/21/cordova-registry.html), and may not works properly,
Please feel free to give us feedback, thx~
